/* isarri_contract.h -- the caller contract for isarri.
 *
 * Include this, not isarri.h directly: isarri.h is generated by Isabelle-LLVM and carries only the
 * raw signature.
 *
 * Every hypothesis of the correctness theorem is proof-side only. Isabelle ASSERTs and Sepref
 * preconditions do not compile to runtime checks, so violating one does not produce an error; it
 * produces an answer the theorem says nothing about. No mathematical or memory-validity obligation
 * is checked at run time; the code only bounds its stores by out_cap (item 7).
 *
 * WARNING: *out_substituted is NOT a success flag. It only says which path produced the output (see OUTPUT);
 * the output is valid whatever its value, and the theorem says nothing about it.
 * WARNING: not thread-safe. The runtime allocator keeps global free lists without locks, so
 * concurrent calls are unsupported even when their buffers are disjoint.
 */
#ifndef ISARRI_CONTRACT_H
#define ISARRI_CONTRACT_H 1

#include "isarri.h"

/* void isarri(int64_t *out_pos_count, gmp_mpz_struct **out_pos_lna, gmp_mpz_struct **out_pos_rnb,
 *             int64_t *out_pos_k,
 *             int64_t *out_neg_count, gmp_mpz_struct **out_neg_lna, gmp_mpz_struct **out_neg_rnb,
 *             int64_t *out_neg_k,
 *             int64_t *out_xs0, int64_t *out_substituted,
 *             int64_t out_cap, int64_t nfloor, int64_t hcap, int64_t dlt,
 *             int64_t len, gmp_mpz_struct **coeff_ptrs);
 *
 * Isolates every real root of P(x) = sum_i coeff_ptrs[i] * x^i (len coefficients, ascending
 * degree). The polynomial is split at 0; the positive and negative halves are reported separately.
 *
 * THEOREM: isarri_correct (thys/proofs/Isarri/Isarri_Correct.thy), a total-correctness Hoare triple:
 * when the obligations below hold, the call terminates, and after it, for the positive
 * half and, in reflected coordinates, the negative half: every emitted window isolates exactly one
 * real root; every root of that sign lies in the open interior of some window or is some point
 * window; no root lies in two windows; *out_pos_count and *out_neg_count equal the numbers of
 * distinct positive and negative real roots; the first min(count, out_cap) slots of the output
 * arrays hold those windows; *out_xs0 is 1 exactly when coeff_ptrs[0] is 0.
 *
 * CALLER OBLIGATIONS -- none is checked at run time except (7):
 *
 *   1. SQUAREFREE input, the standard precondition of subdivision isolators: pass the squarefree
 *      part P / gcd(P, P'), which has the same distinct roots. For a polynomial with a repeated
 *      factor the call need not terminate, and windows it returns need not isolate its roots.
 *   2. CANONICAL coefficients: the leading coefficient coeff_ptrs[len-1] is nonzero.
 *   3. len >= 2.
 *   4. LENGTH AND DEPTH: (258 * mu' + 1) * len < 2^40, where mu' is the bisection-depth bound of
 *      the normalised search box at the deflating solver's threshold. (The formal predicate also
 *      lists len < 2^40, len + 3 < 2^63, and (kD + 1) * len < 2^40 and kD * (len - 1) < 2^63 for
 *      every depth kD <= 258 * mu'; all of them follow from this one.) mu' grows with log2 of the
 *      inverse root separation, so this is a separation floor of roughly 2^(-2^40 / (258 * len)),
 *      e.g. about 2^-426000 at len = 10^4. It is LINEAR in the depth: the loops' worklists are
 *      depth-first stacks.
 *   5. COEFFICIENT SIZE AND ROOT-BOUND WORD FIT: every coefficient c has |c| < 2^(2^63 - len - 2),
 *      i.e. at most 2^63 - len - 2 bits (kiou_headroom), and for the root-bound exponent k of each
 *      half, k * len < 2^63 and k + mu + 3 < 2^63.
 *   6. hcap < 2^63.
 *   7. OUTPUT CAPACITY (a run-time behaviour, not a check): the output arrays hold out_cap entries each. The code cannot
 *      check an array's size, but it compares the number of roots with out_cap and never stores
 *      more than out_cap windows. The counts are written truthfully and may exceed out_cap, so
 *      *out_*_count > out_cap means windows were dropped.
 *   8. THE REDUCED POLYNOMIAL. Let h be the gcd of the exponents with nonzero coefficient. If
 *      d = gcd(h, hcap) is even and >= 2, then P(x) = Q(x^d). If moreover len >= 10 and
 *      len >= nfloor, so that the substitution is attempted, the theorem assumes obligations 1-5
 *      for Q as well; otherwise it assumes nothing about Q. Q's coefficients
 *      are coeff_ptrs[0], coeff_ptrs[d], coeff_ptrs[2d], ... Obligations 1-3 for Q follow from
 *      P's; the depth bounds of 4 and 5 need not, because x -> x^d compresses roots near zero, so
 *      Q's root separation can be smaller than P's, e.g. P(x) = (2^80 x^2 - 1)(2^80 x^2 - 4) = Q(x^2).
 *   9. MEMORY MODEL: the two count cells and the two flag cells are allocated 64-bit word cells;
 *      coeff_ptrs is a block of exactly len pointers, each to its own initialised GMP integer laid
 *      out as mpz_t, with pairwise disjoint storage; each output mpz array holds out_cap initialised mpz_t objects with pairwise disjoint storage
 *      (their values may coincide, e.g. all zero); each
 *      exponent array holds out_cap words; no output cell overlaps another output cell or the input;
 *      len, out_cap, nfloor, hcap and dlt are non-negative.
 *
 * Obligations 1-5 summarise the precondition dsc_isolate_all_split_defl_pre, whose Isabelle
 * definition (thys/refine/kiou_bound_defl/Kiou_Bound_Defl_Reflect.thy) is the authoritative statement;
 * 6 is the theorem's hcap premise; 8 its premise on pow_sub_extract d xs; 9 the separation-logic
 * precondition.
 *
 * OUTPUT:
 *   - Window i of the positive half is the open interval (out_pos_lna[i], out_pos_rnb[i]) / 2^out_pos_k[i].
 *   - THE NEGATIVE HALF IS IN REFLECTED COORDINATES: window i contains the root in the open interval
 *         ( -out_neg_rnb[i] / 2^out_neg_k[i] , -out_neg_lna[i] / 2^out_neg_k[i] ).
 *     Negate both endpoints and swap them.
 *   - A window with equal endpoints is a point window: that point is a root.
 *   - Windows are root-disjoint, not set-disjoint: two windows may overlap in a root-free gap.
 *   - The output mpz_t slots must be initialised before the call; the function writes into them.
 *   - *out_substituted is informational and the theorem says nothing about it (the theory and the
 *     IR call it out_ok). 1 means the substitution
 *     produced the output; 0 means the degree <= 8 path or the deflating solve produced it (the
 *     latter also when a substitution was attempted but its precision search reached dlt). The
 *     output is valid in both cases.
 *
 * PARAMETERS (the theorem holds for every setting that satisfies obligations 6, 8 and 9; all three
 * can change which path runs and hence the windows returned, and hcap also decides, through
 * d = gcd(h, hcap), whether obligation 8 applies):
 *   nfloor  minimum len for attempting power substitution (benchmarks used 22)
 *   hcap    the substitution exponent is gcd(h, hcap) (benchmarks used 32)
 *   dlt     cap on the precision search when mapping windows back (benchmarks used 8)
 * Any non-negative value is safe: before mapping windows back, a run-time guard requires h < 1024,
 * dlt < 1024, a reduced length below 2^20 and every reduced window's exponent below 2^20, and
 * otherwise hands the input to the deflating solver, so no back-map exponent can overflow.
 *
 * CAPACITY bounds only what is stored: the solver builds both lists in full whatever out_cap is,
 * so a small out_cap does not bound memory use; out_cap = 0 yields the counts alone.
 *
 * A CONVENIENCE LAYER, wrapper/isarri_simple.h, sets up this memory layout, checks obligations 2-3,
 * maps the negative half back, sorts the windows and serialises calls with a mutex. It is NOT
 * verified.
 *
 * THREADING: not thread-safe. The runtime allocator (runtime/lib_isabelle_llvm.c) keeps per-size
 * free lists without locks, so no two calls may run at once, even on disjoint buffers. Serialise
 * the calls (wrapper/isarri_simple.c does, with a mutex).
 *
 * GMP LIMITS: GMP terminates the process if an integer would exceed its own size limit; like
 * memory exhaustion, this ends the call without an answer.
 *
 * MEMORY: the theorem's memory model has no allocation failure. If the system allocator fails, the
 * runtime (and GMP) abort the process: exhausting memory ends the call without an answer, never
 * with a wrong one.
 *
 * PLATFORM: the theorem models a GMP integer as gmp_mpz_struct (int32 alloc, int32 size, pointer to
 * 64-bit limbs), and callers pass GMP's own mpz_t objects. That correspondence is outside the proof.
 * It is checked at compile time below whenever <gmp.h> is included before this header: 64-bit
 * limbs, and the same size, alignment and field offsets as GMP's __mpz_struct. Tested
 * configuration: macOS on arm64 (Apple M4), Apple clang 21, GMP 6.3.0, with
 * runtime/lib_isabelle_llvm.c as the runtime.
 */

#if defined(__GMP_H__)
#include <stddef.h>
#ifdef __cplusplus
#define ISARRI_STATIC_ASSERT static_assert
#define ISARRI_ALIGNOF alignof
#else
#define ISARRI_STATIC_ASSERT _Static_assert
#define ISARRI_ALIGNOF _Alignof
#endif
ISARRI_STATIC_ASSERT(GMP_LIMB_BITS == 64, "isarri: GMP must use 64-bit limbs");
ISARRI_STATIC_ASSERT(sizeof(gmp_mpz_struct) == sizeof(__mpz_struct), "isarri: mpz_t size differs");
ISARRI_STATIC_ASSERT(ISARRI_ALIGNOF(gmp_mpz_struct) == ISARRI_ALIGNOF(__mpz_struct),
                     "isarri: mpz_t alignment differs");
ISARRI_STATIC_ASSERT(offsetof(gmp_mpz_struct, field0) == offsetof(__mpz_struct, _mp_alloc) &&
                     sizeof(((__mpz_struct *)0)->_mp_alloc) == sizeof(int32_t),
                     "isarri: mpz_t alloc field differs");
ISARRI_STATIC_ASSERT(offsetof(gmp_mpz_struct, field1) == offsetof(__mpz_struct, _mp_size) &&
                     sizeof(((__mpz_struct *)0)->_mp_size) == sizeof(int32_t),
                     "isarri: mpz_t size field differs");
ISARRI_STATIC_ASSERT(offsetof(gmp_mpz_struct, field2) == offsetof(__mpz_struct, _mp_d),
                     "isarri: mpz_t limb pointer differs");
#undef ISARRI_STATIC_ASSERT
#undef ISARRI_ALIGNOF
#endif

#endif
