// Generated by Isabelle-LLVM. Do not modify.
#ifndef _ISARRI_H
#define _ISARRI_H 1


#include <stdint.h>


typedef struct gmp_mpz_struct gmp_mpz_struct;

typedef struct gmp_mpz_struct {
  int32_t field0;
  int32_t field1;
  int64_t*field2;
} gmp_mpz_struct;

int32_t isarri_mpz_sgn(gmp_mpz_struct*);
void isarri_mpz_free(gmp_mpz_struct*);
void isarri(int64_t*, gmp_mpz_struct**, gmp_mpz_struct**, int64_t*, int64_t*, gmp_mpz_struct**, gmp_mpz_struct**, int64_t*, int64_t*, int64_t*, int64_t, int64_t, int64_t, int64_t, int64_t, gmp_mpz_struct**);

#endif
